execution.default.selectingCapturedObjectSelectorMethod="XPATH"
report.videoRecorderOption="{\\"enable\\"\:false,\\"useBrowserRecorder\\"\:true,\\"videoFormat\\"\:\\"AVI\\",\\"videoQuality\\"\:\\"LOW\\",\\"recordAllTestCases\\"\:false,\\"allowedRecordIfFailed\\"\:true,\\"allowedRecordIfPassed\\"\:false}"
plugin.reloadOption="ONLINE"
mailConfig.encryptionEnabled=false
mailConfig.host="smtp.gmail.com"
mailConfig.port="587"
mailConfig.username="jeraldaj85@gmail.com"
mailConfig.password="Manutd@9523"
mailConfig.securityProtocol="SSL"
mailConfig.attachment=true
mailConfig.subject="Katalon Summary Report for ${suiteName} ${suiteCollectionName}"
mailConfig.cc=""
mailConfig.bcc=""
mailConfig.useUsernameAsSender=true
mailConfig.sender="jeraldaj85@gmail.com"
mailConfig.reportRecipients="jeraldaj85@gmail.com"
mailConfig.reportFormat="[\\n  \\"HTML\\"\\n]"
mailConfig.sendTestSuiteReport=true
mailConfig.sendReportTestFailedOnly=false
mailConfig.sendTestSuiteCollectionReport=false
mailConfig.skipIndividualTestSuiteReport=false
